# Generated by Django 2.2.2 on 2020-03-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_fitnessplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessPlan',
        ),
    ]
